In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv(r"D:\PYTHON\tp1\Prices%20house.csv")
df=pd.DataFrame(data)
df

,Size,Number of rooms,Location,Distance of the center,Years of construction,Date,Country,Build quality,Price final
0,0.935726,0.921034,0.050417,0.173085,0.139500,12/09/1995,Ghana,7,643428
1,0.945854,0.084170,0.211671,0.080723,0.980385,17/06/2015,Christmas Island,4,939085
2,0.425973,0.190178,0.221490,0.443040,0.768223,22/10/2001,Cocos (Keeling) Islands,8,149126
3,0.599944,0.237729,0.584219,0.387131,0.034368,05/04/2008,South Georgia and the South Sandwich Islands,5,951468
4,0.293112,0.322832,0.065941,0.615047,0.849242,15/12/1997,Niger,7,357705
...,...,...,...,...,...,...,...,...,...
19995,0.233252,0.767280,0.617955,0.872762,0.395947,03/07/2017,Serbia,6,323517
19996,0.761047,0.412396,0.923288,0.944881,0.958778,12/04/2023,Saint Martin,6,733778
19997,0.831551,0.199999,0.744946,0.971285,0.388012,16/04/2000,Cambodia,2,114595
19998,0.839408,0.216327,0.528366,0.412535,0.009789,11/09/2017,New Caledonia,6,954607
19999,0.944656,0.823829,0.805750,0.749896,0.526777,19/02/2016,Mali,6,288551

BUILD QUALITY WITH PRICE

In [2]:
df['build_price']=df['Price final']/df['Build quality']
df

,Size,Number of rooms,Location,Distance of the center,Years of construction,Date,Country,Build quality,Price final,build_price
0,0.935726,0.921034,0.050417,0.173085,0.139500,12/09/1995,Ghana,7,643428,91918.285714
1,0.945854,0.084170,0.211671,0.080723,0.980385,17/06/2015,Christmas Island,4,939085,234771.250000
2,0.425973,0.190178,0.221490,0.443040,0.768223,22/10/2001,Cocos (Keeling) Islands,8,149126,18640.750000
3,0.599944,0.237729,0.584219,0.387131,0.034368,05/04/2008,South Georgia and the South Sandwich Islands,5,951468,190293.600000
4,0.293112,0.322832,0.065941,0.615047,0.849242,15/12/1997,Niger,7,357705,51100.714286
...,...,...,...,...,...,...,...,...,...,...
19995,0.233252,0.767280,0.617955,0.872762,0.395947,03/07/2017,Serbia,6,323517,53919.500000
19996,0.761047,0.412396,0.923288,0.944881,0.958778,12/04/2023,Saint Martin,6,733778,122296.333333
19997,0.831551,0.199999,0.744946,0.971285,0.388012,16/04/2000,Cambodia,2,114595,57297.500000
19998,0.839408,0.216327,0.528366,0.412535,0.009789,11/09/2017,New Caledonia,6,954607,159101.166667
19999,0.944656,0.823829,0.805750,0.749896,0.526777,19/02/2016,Mali,6,288551,48091.833333

In [4]:
df['Date']=pd.to_datetime(df['Date'],format='%d/%m/%Y')
df['month']=df['Date'].dt.month
df['year']=df['Date'].dt.year
df

,Size,Number of rooms,Location,Distance of the center,Years of construction,Date,Country,Build quality,Price final,build_price,month,year
0,0.935726,0.921034,0.050417,0.173085,0.139500,1995-09-12,Ghana,7,643428,91918.285714,9,1995
1,0.945854,0.084170,0.211671,0.080723,0.980385,2015-06-17,Christmas Island,4,939085,234771.250000,6,2015
2,0.425973,0.190178,0.221490,0.443040,0.768223,2001-10-22,Cocos (Keeling) Islands,8,149126,18640.750000,10,2001
3,0.599944,0.237729,0.584219,0.387131,0.034368,2008-04-05,South Georgia and the South Sandwich Islands,5,951468,190293.600000,4,2008
4,0.293112,0.322832,0.065941,0.615047,0.849242,1997-12-15,Niger,7,357705,51100.714286,12,1997
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.233252,0.767280,0.617955,0.872762,0.395947,2017-07-03,Serbia,6,323517,53919.500000,7,2017
19996,0.761047,0.412396,0.923288,0.944881,0.958778,2023-04-12,Saint Martin,6,733778,122296.333333,4,2023
19997,0.831551,0.199999,0.744946,0.971285,0.388012,2000-04-16,Cambodia,2,114595,57297.500000,4,2000
19998,0.839408,0.216327,0.528366,0.412535,0.009789,2017-09-11,New Caledonia,6,954607,159101.166667,9,2017
19999,0.944656,0.823829,0.805750,0.749896,0.526777,2016-02-19,Mali,6,288551,48091.833333,2,2016

In [5]:
df['ytob']=np.where(df['year']>=2000,1,0)
df

,Size,Number of rooms,Location,Distance of the center,Years of construction,Date,Country,Build quality,Price final,build_price,month,year,ytob
0,0.935726,0.921034,0.050417,0.173085,0.139500,1995-09-12,Ghana,7,643428,91918.285714,9,1995,0
1,0.945854,0.084170,0.211671,0.080723,0.980385,2015-06-17,Christmas Island,4,939085,234771.250000,6,2015,1
2,0.425973,0.190178,0.221490,0.443040,0.768223,2001-10-22,Cocos (Keeling) Islands,8,149126,18640.750000,10,2001,1
3,0.599944,0.237729,0.584219,0.387131,0.034368,2008-04-05,South Georgia and the South Sandwich Islands,5,951468,190293.600000,4,2008,1
4,0.293112,0.322832,0.065941,0.615047,0.849242,1997-12-15,Niger,7,357705,51100.714286,12,1997,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.233252,0.767280,0.617955,0.872762,0.395947,2017-07-03,Serbia,6,323517,53919.500000,7,2017,1
19996,0.761047,0.412396,0.923288,0.944881,0.958778,2023-04-12,Saint Martin,6,733778,122296.333333,4,2023,1
19997,0.831551,0.199999,0.744946,0.971285,0.388012,2000-04-16,Cambodia,2,114595,57297.500000,4,2000,1
19998,0.839408,0.216327,0.528366,0.412535,0.009789,2017-09-11,New Caledonia,6,954607,159101.166667,9,2017,1
19999,0.944656,0.823829,0.805750,0.749896,0.526777,2016-02-19,Mali,6,288551,48091.833333,2,2016,1

In [6]:
df.isnull().sum().sum()

0